framework_lib/src/ccgx/device.rs
framework_lib/src/ccgx/mod.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/mod.rs

Fixes ccgx info on AMD systems where the cros_ec driver doesn't work yet.

ccgx: Use same CrosEc driver as everywhere else

---

README.md
framework_lib/src/chromium_ec/command.rs
framework_lib/src/chromium_ec/commands.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs

The minimum limit cannot be changed.
Tested on platforms:
- Intel 12th Gen with BIOS 3.07
- AMD 13th inch with BIOS 3.04
Tested with drivers:
- portio on UEFI Shell
- portio on Linux
- cros_ec on Linux
Examples:
```
> framework_tool --driver portio --charge-limit
Minimum 0%, Maximum 100%
> framework_tool --charge-limit 90
Minimum 0%, Maximum 90%
> framework_tool --driver portio --fp-brightness
Fingerprint LED Brightness: 55%
> framework_tool --fp-brightness low
Fingerprint LED Brightness: 15%
```
Fixes #5

Add commands to get/ set charge limit and FP brightness

---

framework_lib/src/ccgx/device.rs
framework_lib/src/ccgx/mod.rs

Before:
```
Left / Ports 01
Silicon ID:     0x3000
Mode:           MainFw
Flash Row Size: 128 B
Bootloader Version: Base: 3.4.0.420,  App: 0.0.2 (Notebook)
FW1 (Backup) Version: Base: 3.4.0.425,  App: 0.1.44 (Notebook)
FW2 (Main)   Version: Base: 3.4.0.425,  App: 0.1.44 (Notebook)
```
After:
```
Left / Ports 01
Silicon ID:     0x3000
Mode:           MainFw
Flash Row Size: 128 B
Bootloader Version:   Base: 3.4.0.420,  App: 0.0.02 (Notebook)
FW1 (Backup) Version: Base: 3.4.0.425,  App: 0.1.44 (Notebook)
FW2 (Main)   Version: Base: 3.4.0.425,  App: 0.1.44 (Notebook)
```

ccgx: Lign up Version info nicely

---

Cargo.lock
framework_lib/Cargo.toml
framework_lib/src/chromium_ec/command.rs
framework_lib/src/chromium_ec/commands.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/chromium_ec/portio.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs
framework_lib/src/ec_binary.rs
framework_lib/src/util.rs

This is not official endorsement that you should flash EC firmware.
Use on your own risk.
Flashing RO firmware is disabled, this should prevent people from bricking their systems.
Framework systems don't use RW firmware at the moment.

Allow flashing EC firmware

---

framework_lib/src/ccgx/device.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs
framework_lib/src/smbios.rs
framework_lib/src/util.rs

If the platform couldn't be matched by SMBIOS, now you can select the platform config manually on the commandline.
This is not usually needed, just for advanced users.
For example:
```
framework_tool --test --driver portio --pd-addrs 8 64 --pd-ports 6 6 --has-mec true
framework_tool --test --driver portio --pd-addrs 8 64 --pd-ports 6 7 --has-mec true
framework_tool --test --driver portio --pd-addrs 66 64 --pd-ports 1 2 --has-mec false
```

Allow customizing platform if not matched

---

framework_lib/src/commandline/mod.rs
framework_lib/src/csme.rs

After CSME update, the three versions will be different.
Fixes #35

framework_lib: Parse CMSE versions correctly

---

framework_lib/src/ccgx/device.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/esrt/mod.rs
framework_lib/src/smbios.rs
framework_lib/src/util.rs

Allow customizing platform if not matched

framework_lib: Add Meteorlake definitions

---

framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs
framework_lib/src/power.rs

Useful when there is no OS driver or when it's not working.
E.g. on FreeBSD or on early Intel systems with Linux kernel bug.

framework_lib: Read ALS sensor

---

.github/workflows/ci.yml
Cargo.lock
Cross.toml
framework_lib/Cargo.toml
framework_lib/src/ccgx/mod.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/esrt/mod.rs
framework_lib/src/lib.rs
framework_lib/src/util.rs

I downloaded the binary from actions upload and it can run on FreeBSD 15-CURRENT.

gh-actions: Add FreeBSD cross compilation

---

framework_lib/src/chromium_ec/input_deck.rs

Added in EC firmware in https://github.com/FrameworkComputer/EmbeddedController/commit/20999fffdfc744b77fb11b258d1650773e1ec15e

chromium_ec: Add full-width input module

---

Cargo.lock
framework_lib/Cargo.toml
framework_lib/src/commandline/mod.rs
framework_lib/src/esrt/mod.rs

```
> target\debug\framework_tool.exe --esrt`
ESRT Entry 0
Name:    MtlRetimer01
GUID:    c57fd615-2ac9-4154-bf34-4dc715344408
Version: CF (207)
ESRT Entry 1
Name:    MtlCsme
GUID:    32d8d677-eebc-4947-8f8a-0693a45240e5
Version: 85D (2141)
ESRT Entry 2
Name:    MtlBios
GUID:    72cecb9b-2b37-5ec2-a9ff-c739aabaadf3
Version: 301 (769)
ESRT Entry 3
Name:    MtlRetimer23
GUID:    bdffce36-809c-4fa6-aecc-54536922f0e0
Version: CF (207)
Could not find and parse ESRT table.
```

windows: Get ESRT from WMI

---

framework_lib/src/ccgx/device.rs
framework_lib/src/ccgx/mod.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/power.rs

On TGL we modified the base version, not the app version. `-version` would show the incorrect version.
`--pd-info` shows both.
```
FS1:\> framework_tool.efi --versions
UEFI BIOS
Version:        03.19
Release Date:   05/29/2023
EC Firmware
Build version:  "hx20_v0.0.1-f6d6b92 2023-05-26 00:03:59 runner@fv-az504-734"
RO Version:     "hx20_v0.0.1-f6d6b92"
RW Version:     "hx20_v0.0.1-f6d6b92"
Current image:  RO
PD Controllers
Right (01)
Main:       3.4.0.2575 (Active)
Backup:     3.4.0.2575
Left  (23)
Main:       3.4.0.2575 (Active)
Backup:     3.4.0.2575
Retimers
Left:           0xCF (207)
Right:          0xCF (207)
```

tgl: Fix PD controller version

---

framework_lib/src/esrt/mod.rs

`ENODEV`, most likely from here: https://github.com/freebsd/freebsd-src/blob/main/sys/dev/efidev/efirt.c#L386

freebsd: Don't panic if can't ioctl ESRT

---

framework_lib/src/commandline/mod.rs

Currently, the charge limit accepts values all the way up to 255. I'd wager a guess this isn't intentional. 
(code isn't tested, so I would recommend testing it before merging!)

charge_limit: cap percentage to 100%

---

Cargo.lock
framework_tool/Cargo.toml
framework_tool/build.rs

Otherwise it won't run on freshly installed Windows systems because vcruntime is missing.
Must `cargo build --release` to get it. Debug builds won't have it linked statically.

framework_tool: Statically link CRT

---

README.md
framework_lib/src/ccgx/mod.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs
framework_lib/src/power.rs
framework_lib/src/smbios.rs
framework_lib/src/util.rs
framework_tool/src/main.rs
framework_uefi/src/main.rs

This will check if versions match and return 0 if match or 1 if not match.
This can run in UEFI shell etc.

Create version check function

---

framework_lib/src/ccgx/mod.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/power.rs

Example on Intel Core Ultra:
```
> sudo ./framework_tool --test
Self-Test
SMBIOS Platform:     IntelCoreUltra1
Dump EC memory region
00000000: 7f82 7378 99ff ffff ffff ffff ffff ffff  .sx............
00000010: c410 ffff ffff ffff ffff ffff ffff ffff  ................
00000020: 4543 0102 0201 0103 0000 0000 0000 0000  EC..............
00000030: 0500 0000 0000 0000 0000 0000 0000 0000  ................
00000040: de44 0000 210a 0000 640b 0000 0b01 0000  .D..!...d.......
00000050: 4b0f 0000 783c 0000 a00f 0000 3b00 0000  K...x<......;...
00000060: 4e56 5400 0000 0000 4652 414e 4757 4100  NVT.....FRANGWA.
00000070: 3031 3130 0000 0000 4c49 4f4e 0000 0000  0110....LION....
00000080: 1300 0000 0000 0000 0000 0000 0000 0000  ................
00000090: 0000 0000 0000 0000 0000 0000 0000 0000 …
```

Prettier --test command

---

framework_lib/src/chromium_ec/command.rs
framework_lib/src/chromium_ec/commands.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs

Example:
```
> sudo ./target/debug/framework_tool --get-gpio chassis_open_l
Getting GPIO value chassis_open_l: true
```

framework_lib: Implement getting GPIO value

---

framework_lib/src/chromium_ec/portio.rs
framework_lib/src/chromium_ec/windows.rs
framework_lib/src/esrt/mod.rs

Still works with driver from dhowett/FrameworkWindowsUtils

windows: Fix host commands with crosecbus driver

---

framework_lib/src/ccgx/mod.rs

ccgx: Format PD version as decimal on 11th Gen

---

framework_lib/src/chromium_ec/mod.rs
framework_lib/src/smbios.rs

For convenience when using as a library.

Add export and Debug deriving

---

framework_lib/src/chromium_ec/commands.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs

On new EC:
```
> framework_tool.exe --fp-led-level medium
Fingerprint LED Brightness
Requested:  Medium
Brightness: 40%
> framework_tool.exe --fp-led-level high
Fingerprint LED Brightness
Requested:  High
Brightness: 55%
> framework_tool.exe --fp-brightness
Fingerprint LED Brightness
Requested:  High
Brightness: 55%
> framework_tool.exe --fp-brightness 32
Fingerprint LED Brightness
Requested:  Custom
Brightness: 32%
> framework_tool.exe --fp-led-level ultra-low
Fingerprint LED Brightness
Requested:  UltraLow
Brightness: 8%
> framework_tool.exe --fp-led-level auto
Fingerprint LED Brightness
Requested:  Auto
Brightness: 55%
> framework_tool.exe --fp-brightness
Fingerprint LED Brightness
Requested:  Auto
Brightness: 8%
```
On old EC:
```
> sudo framework_tool --fp-brightness
Fingerprint LED …
```

fp-brightness: Add support for V1 host command

---

framework_lib/src/chromium_ec/commands.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs

Must also have EC support. Will be included in Framework 13 - AMD Ryzen AI 300 first and then gradually backported.
First step towards #37.

framework_lib: Add ultra-low powerbutton brightness

---

framework_lib/src/chromium_ec/commands.rs

Was added to EC in
fwk: add device_complete
1753269e7e2c03c6ef667ae59fd594d2b753533f

chromium: Add device_complete to diags

---

Cargo.lock
framework_lib/Cargo.toml
framework_lib/src/chromium_ec/command.rs
framework_lib/src/chromium_ec/commands.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs
rgbkbd.py

Yes, called rgbkbd because of the host command and to match ectool.
But we are actually planning to use it for the Framework Deskop's ARGB header (with fans, etc.)
For example:
```
sudo framework_tool --rgbkbd 0 0xFF0000 0x00FF00 0x0000FF
sudo framework_tool --rgbkbd 0 0 0 0 0 0 0 0 0
sudo framework_tool --rgbkbd 2 0xFF0000
```

Add support for RGB command

---

framework_lib/src/camera.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/lib.rs

Example on Framework 12:
```
> framework_tool --versions
[...]
Framework Laptop 12 Webcam Module
Firmware Version: 0.1.6
```
Example on Framework 13:
```
> framework_tool --versions
[...]
Laptop Webcam Module (2nd Gen)
Firmware Version: 1.1.1
```
Tested on:

camera: Print firmware version of camera

---

README.md
framework_lib/src/commandline/mod.rs
framework_lib/src/lib.rs
framework_lib/src/touchpad.rs

Example on Framework 13:
```
> framework_tool --version
[...]
Touchpad
IC Type:           0274
Firmware Version: v0704
```

touchpad: Show IC type and firmware version

---

.github/workflows/ci.yml
framework_lib/src/chromium_ec/mod.rs
framework_tool/Cargo.toml

So that the vcruntime DLL is built in and runs on freshly installed windows systems.

windows: Upload release binary

---

framework_lib/src/chromium_ec/windows.rs
framework_lib/src/commandline/mod.rs

Trying it out without running as admin to cause it to fail accessing the driver.
```
> cargo run --no-default-features --features "windows" -p framework_tool -- --test
Self-Test
SMBIOS Platform:     Framework13AmdAi300
Dump EC memory region
[ERROR] Failed to find Windows driver. Error { code: HRESULT(0x80070005), message: "Access is denied." }
[ERROR] Failed to communicate with EC. Reason: "Failed to initialize"
Failed to read EC memory region
FAILED!!
Error: "Fail"
error: process didn't exit successfully: `target\debug\framework_tool.exe --test` (exit code: 1)
> cargo run --no-default-features --features "windows" -p framework_tool -- --test
Self-Test
SMBIOS Platform:     Framework13AmdAi300
Dump EC memory region
thread 'main' panicked at framework_lib\src\chromium_ec\windows.rs:46:14: …
```

windows: Don't panic if driver not installed

---

framework_lib/src/touchpad.rs

```
> framework_tool --versions
[...]
Touchpad
IC Type:           0239
Firmware Version: v0E07
```

framework12: Support reading touchpad version

---

README.md
framework_lib/Cargo.toml
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs
framework_lib/src/lib.rs
framework_lib/src/touchscreen.rs
framework_lib/src/touchscreen_win.rs

```
> framework_tool --versions
[...]
Touchscreen
Firmware Version: v7.0.0.4.0.0.0.0
USI Protocol:     false
MPP Protocol:     true
> framework_tool --touchpad-enable true
> framework_tool --touchpad-enable false
```

touchscreen: Dump firmware version and protocol

---

framework_lib/Cargo.toml
framework_lib/src/chromium_ec/command.rs
framework_lib/src/chromium_ec/commands.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs

TEST=Tested on platform to overwrite the serial
And I can see the serial updates to the new value after rebooting the EC.

add commands to read/write gpu serial

---

framework_lib/src/commandline/mod.rs

On platforms that don't have an updateable retimer, we don't need to show anything. Currently it would show as "Unknown".

Don't show retimer as unknown if none present

---

framework_lib/src/ccgx/hid.rs

Unused variable because we immediately override it.

freebsd: Remove warning

---

framework_lib/src/chromium_ec/mod.rs

Now it can get all of the EC console buffer.
I see ~100 lines. Much more than the previous ~10 lines.
Follow also seems to properly work now.
A good way to force messages to appear on the console is to plug in or unplug a charger, or to close and open the lid.
TEST=`framework_tool --console recent` shows the same output as `ectool console` 
TEST=`framework_tool --console follow` keeps properly refreshing endlessly.

chromium_ec: Fix reading EC console

---

.github/workflows/ci.yml

This reverts commit ccd8a3639e7116bbf0ff11e943436d7849223298.
Fixed by https://github.com/cross-rs/cross/pull/1674

Revert "gh-actions: Disable FreeBSD builds"

---

framework_lib/src/commandline/mod.rs
framework_lib/src/inputmodule.rs
framework_lib/src/lib.rs

All types of Keyboard and LED matrix
```
> framework_tool --versions
[...]
Laptop 16 Numpad
Firmware Version: 0.2.9
Location: [X] [ ] [ ]       [ ] [ ]
Laptop 16 ANSI Keyboard
Firmware Version: 0.2.9
Location: [ ] [ ] [X]       [ ] [ ]
[...]
```
```
> framework_tool --versions
[...]
LED Matrix
Firmware Version: 0.2.0
Location: [X] [ ] [ ]       [ ] [ ]
Laptop 16 ANSI Keyboard
Firmware Version: 0.2.9
Location: [ ] [x] [ ]       [ ] [ ]
LED Matrix
Firmware Version: 0.2.0
Location: [ ] [ ] [ ]       [ ] [x]
[...]
```

Show firmware version of Framework 16 Inputmodules

---

EXAMPLES.md
README.md
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs

```
> framework_tool.exe --expansion-bay
Expansion Bay
Enabled:       true
Has fault:     false
Hatch closed:  true
Board:         DualInterposer
Serial Number: FRAXXXXXXXXXXXXXXX
```

Add --expansion-bay command to print info

---

README.md
completions/bash/framework_tool
completions/zsh/_framework_tool
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs
framework_lib/src/util.rs
support-matrices.md

Previously only Framework 16, expand to Framework 12.
```
> sudo framework_tool --inputdeck
Input Deck
Chassis Open:        true
Power Button Board:  Present
Audio Daughterboard: Present
Touchpad:            Present
```
And Framework 13
```
> sudo framework_tool --inputdeck
Input Deck
Chassis Open:        false
Audio Daughterboard: Present
Touchpad:            Present
```

--input-deck: Print Framework12 and Framework 13 input deck status

---

EXAMPLES.md
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs
framework_lib/src/touchscreen.rs
framework_lib/src/touchscreen_win.rs

On Windows and Linux:
```
> sudo framework_tool --versions
[...]
Stylus
Serial Number:    28C1A00-12E71DAE
Vendor ID:        32AC (Framework Computer)
Product ID:       002B (Framework Stylus)
Firmware Version: FF.FF
[...]
```
Only on Linux:
```
> sudo framework_tool --stylus-battery
Stylus Battery Strength: 77%
```

Get information from USI Stylus

---

framework_lib/src/chromium_ec/command.rs
framework_lib/src/chromium_ec/commands.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs

After the system turns off and no AC power is present, the EC waits a few seconds and then  turns off completely.
Using this command we can find out what that delay is and change it.
```
> framework_tool.exe --ec-hib-delay 30
EC Hibernation Delay: 30s
```

Add command to set EC hibernation delay

---

EXAMPLES.md
framework_lib/src/commandline/clap_std.rs

Following are fixed now
```
> sudo framework_tool --charge-rate-limit 80 0.8
> sudo framework_tool --charge-current-limit 80 2000
```
Reported by: github.com/tjkirch

Fix charge limit based on battery charge

---

framework_lib/src/ccgx/device.rs
framework_lib/src/chromium_ec/i2c_passthrough.rs
framework_lib/src/chromium_ec/mod.rs

Tested i2c_read:
Note that the port number does not seem to always match the right one.
```
i2c_read(0x05, 0x29, 0x04, 0x08)
i2c_read(ec, 0x07, 0x18, 0x00, 0x01)
i2c_read(ec, 0x07, 0x18, 0x18, 0x01)
i2c_read(ec, 0x07, 0x18, 0x22, 0x01)
i2c_read(ec, 0x06, 0x4D, 0xFD, 0x01)
```

Split I2C tunneling out of ccgx module

---

framework_lib/src/chromium_ec/cros_ec.rs
framework_lib/src/chromium_ec/mod.rs

Then users don't manually have to specify `--driver portio` if the cros_ec kernel driver is not loaded.

chromium_ec: Use portio if /dev/cros_ec does not exist

---

README.md
completions/bash/framework_tool
completions/zsh/_framework_tool
framework_lib/src/ccgx/device.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/chromium_ec/portio.rs
framework_lib/src/chromium_ec/portio_mec.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs
framework_lib/src/smbios.rs
framework_lib/src/util.rs
rgbkbd.py

Shouldn't change behavior, but now we don't need to `--has-mec` commandline flag anymore. Previously we needed it when the system type couldn't be detected.

chromioum_ec: Autodetect Microchip EC when using portio

---

framework_lib/src/ccgx/device.rs
framework_lib/src/smbios.rs
framework_lib/src/util.rs

Now even if the platform isn't detected, we can run the commands just fine. For example both of these work (if I comment out the smbios entry):
```
framework_tool --versions
framework_tool --versions --pd-ports 1 2 --pd-addrs 66 64
```
The first one just fails accessing I2C passthrough for the PD ports.
This is the final change to allow just running the tool on any system in as many cases as possible - even if the linux kernel or framework_tool dose not recognize the system.

Don't require PD config if platform isn't detected

---

.github/workflows/ci.yml
README.md
framework_lib/Cargo.toml
framework_lib/src/capsule.rs
framework_lib/src/chromium_ec/command.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/chromium_ec/portio.rs
framework_lib/src/chromium_ec/portio_mec.rs
framework_lib/src/chromium_ec/protocol.rs
framework_lib/src/chromium_ec/windows.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/csme.rs
framework_lib/src/esrt/mod.rs
framework_lib/src/lib.rs
framework_lib/src/touchscreen.rs
framework_lib/src/util.rs
framework_tool/Cargo.toml

Now we can build on Windows and FreeBSD, in addition to previously just Linux: with `cargo build` only!

Simplify features and detect based on OS

---

.github/workflows/ci.yml

If it's not tested on CI, it might break.

gh-actions: Also build on MSRV (1.74)

---

EXAMPLES.md
framework_lib/src/chromium_ec/command.rs
framework_lib/src/chromium_ec/commands.rs
framework_lib/src/chromium_ec/mod.rs

```
> sudo framework_tool --expansion-bay
Expansion Bay
Enabled:       true
No fault:      true
Door  closed:  true
Board:         DualInterposer
Serial Number: FRAXXXXXXXXXXXXXXX
Config:        Pcie4x2
Vendor:        SsdHolder
```

--expansion-bay: Print PCIe config

---

README.md
framework_lib/src/chromium_ec/commands.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs

Another benefit is that you can find out the names of all GPIOs.
```
> sudo framework_tool --get-gpio
ec_espi_rst_l                    0
runpwrok                         1
otg_en                           0
ec_i2c0_clk0                     0
ec_i2c0_sda0                     0
ec_i2c1_clk0                     0
ec_i2c1_sda0                     0
ec_i2c2_clk0                     0
[...]
```

--get-gpio: Return all GPIOs if no name was passed

---

EXAMPLES.md
framework_lib/src/chromium_ec/command.rs
framework_lib/src/chromium_ec/commands.rs
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/power.rs
framework_lib/src/smbios.rs

On Framework 12 (now hides non existant ALS):
```
> framework_tool --sensors -vv
[INFO ] Sensors: 2
[INFO ]   Type: Accel
[INFO ]   Location: Lid
[INFO ]   Chip:     Bma422
[INFO ]   Type: Accel
[INFO ]   Location: Base
[INFO ]   Chip:     Bma422
Accelerometers:
Lid Angle:  126 Deg
Sensor 1:   X=-0.01G Y=+0.80G, Z=+0.59G
Sensor 2:   X=-0.03G Y=+0.00G, Z=+1.00G
```

--sensors: Get information about sensors

---

framework_lib/src/commandline/mod.rs

Works well on Linux. It's disabled by the windows driver at the moment though.
No need to block it in this application, users could also use ectool.

Allow flashing EC RW region

---

framework_lib/src/chromium_ec/portio.rs
framework_lib/src/chromium_ec/portio_mec.rs

Don't let it go through and possibly segfault.
Print an error for the user and exit.
Solved #153

MEC detection: Fail if permission denied

---

.envrc
.gitignore
devenv.lock
devenv.nix
devenv.yaml
nix.md

Must have only Nix and devenv installed
```
devenv shell
cargo build
sudo ./target/debug/framework_tool
```

Add devenv.nix

---

framework_lib/src/ccgx/device.rs
framework_lib/src/ccgx/mod.rs
framework_lib/src/chromium_ec/commands.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/power.rs
framework_lib/src/util.rs

Not all systems have exactly 2 PD controllers, e.g. Framework Desktop has just 1.

--versions: Show any number of PD versions 

---

EXAMPLES.md
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs

Erasing a big section takes too long sometimes and the linux kernel driver times out, so split it up into chunks.

chromium_ec: Erase EC in sections

---

framework_lib/src/power.rs

If the system doesn't have motionsense we can't detect whether ALS is present or not based on EC information.

Show ALS sensor on unknown systems

---

EXAMPLES.md
EXAMPLES_ADVANCED.md
framework_lib/src/chromium_ec/mod.rs
framework_lib/src/commandline/clap_std.rs
framework_lib/src/commandline/mod.rs
framework_lib/src/commandline/uefi.rs

from a file
Example invocation:
boot.efi --flash-gpu-descriptor-file pcie_4x2.bin
TEST=fail: if the write fails we will error correctly TEST=pass: the command will succeed.
TEST=dump contents using ec console:
i2c read I2C_PORT5 0x50 0x0000 16
00000000: 32 ac 00 00 30 00 00 00  00 00 01 00 08 00 00 00 |2...0... ........| And compare to xxd dump of source file to ensure they match.

fw16: add command to write and read expansion bay eeprom

---

EXAMPLES.md
framework_lib/src/chromium_ec/mod.rs

To help debug keyboard/EC issues it's useful to know what the state of that GPIO is. EC uses it to tell the keyboard about system sleep and lid state.
```
> framework_tool --inputdeck
Chassis Closed:   true
Input Deck State: On
Touchpad present: true
SLEEP# GPIO high: true
Positions:
Pos 0: KeyboardA
Pos 1: Disconnected
Pos 2: Disconnected
Pos 3: KeyboardB
Pos 4: Disconnected
```

--inputdeck: On FW16 also print sleep_l gpio state

---

framework_lib/src/commandline/clap_std.rs
framework_lib/src/lib.rs

Current and charge rate limit cannot be read

---

framework_lib/src/commandline/uefi.rs
framework_uefi/Makefile
framework_uefi/src/main.rs

The UEFI tool wouldn't get any arugments when run from a UEFI shell
script. Manually runnning from the shell would work, but not from e.g.
startup.nsh

uefi: Fix shell args when run from a script

---

framework_lib/src/commandline/mod.rs
framework_lib/src/lib.rs
framework_lib/src/usbhub.rs

For example on Framework Desktop:
```
[...]
USB Hub RTL5424
Firmware Version: 1.8.8
[...]
```

Reading usb hub firmware version

---

README.md
framework_lib/src/ccgx/device.rs
framework_lib/src/esrt/mod.rs
framework_lib/src/power.rs
framework_lib/src/smbios.rs
framework_lib/src/util.rs

Most features were already working, now it will provide some extra details and more accurately in some cases.

Add support for Framework 16 AMD AI 300 Series

---

README.md

Using `pacman -Sy <pkg>` to install a package may lead to a partial upgrade and should not be used. Use `pacman -S <pkg>` instead. See https://wiki.archlinux.org/title/Pacman#Installing_packages.

README: fix Archlinux installation instruction
